id: PFDAF43F9
initial_creation_type: input
source_metadata:
  title: Sang Offering
  language: bo
  description: 'Texts on the subject of Sang (bsang/bsangs) or Purificatory Incense
    Smoke Offering:'
  volume:
    7286b27d7342489d94b905dfd26ad32f:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    58f9b33ceb1c4830afd7f701a24288ee:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    2bbee7a81cf844f3a6bbca7a7549984e:
      title: Yarlha Shampo Sang Offering
      parent: Dharma Protectors
    4605e845d3034a29aa7b671341558845:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    862ad9cfc1004812aa7216925589a00d:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    be29d55890ae42b891af8a56356316a0:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Rituals
    bfde02766f404e29ac3c4c464ec30d20:
      title: Sang Offering to Yellow Jambhala
      parent: Rituals
    a49329ec07664f99b9973c1a562d23f0:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Rituals
    38c1e42af8fa44c2a9c500d01bc7a2fa:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Rituals
    07d595fb8362421f85349df82a21a63b:
      title: Brief Sang Offering
      parent: Rituals
    6a299d24393846e8b0b69f4c19985e7d:
      title: Brief Sang Offering to Purify Contamination
      parent: Rituals
    2f0a9c9910f843b59df4fd96eb5390ff:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Rituals
    2ee029ade1f64faaa15f32a8e5aa833f:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Riwo Sangchö
    28bb560f8bb14faba48bf446b2c99223:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Riwo Sangchö
    838480fd2dc0414cb44d6348704f05ab:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Riwo Sangchö
    29c1e2595c0d468185c93af58ae61e09:
      title: A Concise Sang Offering to Tārā
      parent: Tārā
created_at: '2022-03-01T05:40:37.295691'
last_modified_at: '2022-03-01T05:40:37.295694'
statistics:
  total_words: 19400
  total_non_words: 2456
quality:
  non_words_ratio: 0.13
